sudo: false
language: ruby
cache: bundler

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - 2.6.0

git:
  depth: 10

before_install:
  - gem update --system
  - gem install bundler

matrix:
  include:
    - script: bundle exec rake rubocop
      rvm: 2.6.0
    - script: bundle exec rake html_proofer
      rvm: 2.6.0
